server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: airport_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: airport_logs
          __path__: /app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            airport: airport
            event: event
            flight: flight
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          airport:
          event:
          flight:
